version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    platform: linux/amd64
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - keycloak_data:/opt/keycloak/data

  mysql:
    image: mysql:8.3
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # MySQLポートマッピング
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379" # Redisポートマッピング
    volumes:
      - redis_data:/data

volumes:
  keycloak_data:
  mysql_data:
  redis_data: